# Generated by Django 6.0.3 on 2026-03-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('module', models.CharField(choices=[('facturacion', 'Facturación Electrónica'), ('mesa_ayuda', 'Optimización Mesa de Ayuda'), ('gestion_administrativa', 'Gestión Administrativa'), ('sarlaft', 'SARLAFT')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['module', 'name'],
            },
        ),
    ]
