# Generated by Django 6.0.3 on 2026-03-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NecesidadInnovacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255)),
                ('proceso_asociado', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=255)),
                ('situacion_actual', models.TextField(blank=True)),
                ('preocupaciones', models.TextField(blank=True)),
                ('necesidad', models.TextField()),
                ('tipo_objetivo', models.CharField(choices=[('Operativo', 'Operativo'), ('Normativo', 'Normativo'), ('Estrategico', 'Estratégico')], max_length=20)),
                ('recurrencia_mensual', models.PositiveIntegerField()),
                ('duracion_horas', models.DecimalField(decimal_places=1, max_digits=6)),
                ('riesgo', models.IntegerField(choices=[(1, 'Bajo'), (2, 'Medio'), (3, 'Alto')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
