# Generated by Django 6.0.3 on 2026-03-12 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionICR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_agros', models.CharField(max_length=100, unique=True, verbose_name='ID AGROS')),
                ('productor_id', models.CharField(max_length=100, verbose_name='ID Productor')),
                ('tipo_productor', models.CharField(choices=[('pequeño', 'Pequeño Productor'), ('mediano', 'Mediano Productor'), ('grande', 'Grande Productor')], max_length=20)),
                ('valor_credito', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor del Crédito')),
                ('fecha_credito', models.DateField(verbose_name='Fecha del Crédito')),
                ('actividad', models.CharField(max_length=255, verbose_name='Actividad Productiva')),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('evaluado', 'Evaluado')], default='pendiente', max_length=20)),
                ('importado_en', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones_icr', to='execution.execution')),
            ],
            options={
                'verbose_name': 'Operación ICR',
                'verbose_name_plural': 'Operaciones ICR',
                'ordering': ['-importado_en'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionRegla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regla', models.CharField(max_length=100, verbose_name='Código de Regla')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Regla')),
                ('valor_evaluado', models.CharField(max_length=255, verbose_name='Valor Evaluado')),
                ('resultado', models.BooleanField(verbose_name='Cumple')),
                ('evaluado_en', models.DateTimeField(auto_now_add=True)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='icr.operacionicr')),
            ],
            options={
                'verbose_name': 'Evaluación de Regla',
                'verbose_name_plural': 'Evaluaciones de Reglas',
                'ordering': ['evaluado_en'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoICR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elegible', models.BooleanField()),
                ('motivo_no_elegible', models.TextField(blank=True, verbose_name='Motivo de No Elegibilidad')),
                ('porcentaje_icr', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='% ICR')),
                ('valor_icr', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Valor ICR')),
                ('evaluado_en', models.DateTimeField(auto_now_add=True)),
                ('operacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='icr.operacionicr')),
            ],
            options={
                'verbose_name': 'Resultado ICR',
                'verbose_name_plural': 'Resultados ICR',
                'ordering': ['-evaluado_en'],
            },
        ),
    ]
