# Generated by Django 6.0.3 on 2026-03-13 00:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
        ('icr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoICR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('nacional', 'Nacional'), ('complementario', 'Complementario')], max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contrato ICR',
                'verbose_name_plural': 'Contratos ICR',
                'ordering': ['-periodo_inicio'],
            },
        ),
        migrations.RemoveField(
            model_name='evaluacionregla',
            name='operacion',
        ),
        migrations.RemoveField(
            model_name='resultadoicr',
            name='operacion',
        ),
        migrations.AddField(
            model_name='evaluacionregla',
            name='codigo_regla',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='evaluacionregla',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='evaluacionregla',
            name='resultado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='evaluacionregla',
            name='valor_evaluado',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.CreateModel(
            name='BolsaICR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=50)),
                ('valor_asignado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('inscripcion_automatica', models.BooleanField(default=False, help_text='Si activo, las preinscripciones pasan directamente a inscrita sin revisión manual.')),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsas', to='icr.contratoicr')),
            ],
            options={
                'verbose_name': 'Bolsa ICR',
                'verbose_name_plural': 'Bolsas ICR',
                'ordering': ['contrato', 'nombre'],
                'unique_together': {('contrato', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='InscripcionICR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_agros', models.CharField(max_length=100, unique=True, verbose_name='ID AGROS')),
                ('productor_id', models.CharField(max_length=100, verbose_name='ID Productor')),
                ('tipo_productor', models.CharField(choices=[('pequeño', 'Pequeño Productor'), ('mediano', 'Mediano Productor'), ('grande', 'Grande Productor')], max_length=20)),
                ('valor_credito', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha_credito', models.DateField()),
                ('actividad', models.CharField(max_length=255)),
                ('intermediario', models.CharField(blank=True, max_length=255, verbose_name='Intermediario Financiero')),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('sin_evaluar', 'Sin Evaluar'), ('preinscrita', 'Preinscrita'), ('no_elegible', 'No Elegible'), ('inscrita', 'Inscrita'), ('anulada', 'Anulada')], db_index=True, default='sin_evaluar', max_length=20)),
                ('porcentaje_icr', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('valor_icr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('motivo_no_elegible', models.TextField(blank=True)),
                ('consecutivo', models.CharField(blank=True, help_text='Formato AA-NNNNNN, asignado al inscribir.', max_length=20, null=True, unique=True)),
                ('formalizado_en', models.DateTimeField(blank=True, null=True)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('importado_en', models.DateTimeField(auto_now_add=True)),
                ('preinscrito_en', models.DateTimeField(blank=True, null=True)),
                ('bolsa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='icr.bolsaicr')),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones_icr', to='execution.execution')),
                ('formalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones_icr_formalizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción ICR',
                'verbose_name_plural': 'Inscripciones ICR',
                'ordering': ['-importado_en'],
            },
        ),
        migrations.AddField(
            model_name='evaluacionregla',
            name='inscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='icr.inscripcionicr'),
        ),
        migrations.CreateModel(
            name='PorcentajeICR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_productor', models.CharField(choices=[('pequeño', 'Pequeño Productor'), ('mediano', 'Mediano Productor'), ('grande', 'Grande Productor')], max_length=20)),
                ('porcentaje', models.DecimalField(decimal_places=4, help_text='Fracción decimal. Ej: 0.40 = 40%', max_digits=5)),
                ('tope_uvb', models.DecimalField(decimal_places=2, default=Decimal('8700'), help_text='Número máximo de UVBs aplicables al crédito.', max_digits=10)),
                ('valor_uvb', models.DecimalField(decimal_places=2, default=Decimal('1423500'), help_text='Valor COP de 1 UVB (actualizable anualmente).', max_digits=12)),
                ('bolsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porcentajes', to='icr.bolsaicr')),
            ],
            options={
                'verbose_name': 'Porcentaje ICR',
                'verbose_name_plural': 'Porcentajes ICR',
                'ordering': ['bolsa', 'tipo_productor'],
            },
        ),
        migrations.CreateModel(
            name='ReglaICR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tipo_productor', 'Tipo de Productor'), ('valor_minimo', 'Valor Mínimo de Crédito'), ('valor_maximo', 'Valor Máximo de Crédito (SMMLV)'), ('fecha_vigencia', 'Fecha de Vigencia'), ('actividad', 'Actividad Elegible'), ('municipio', 'Municipio/Departamento Habilitado')], max_length=30)),
                ('parametro', models.TextField(help_text='Valor(es) del parámetro según tipo, separados por coma.')),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('bolsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='icr.bolsaicr')),
            ],
            options={
                'verbose_name': 'Regla ICR',
                'verbose_name_plural': 'Reglas ICR',
                'ordering': ['bolsa', 'orden', 'tipo'],
            },
        ),
        migrations.AlterField(
            model_name='evaluacionregla',
            name='regla',
            field=models.ForeignKey(blank=True, help_text='FK a ReglaICR (null si la regla fue eliminada posterior a la evaluación).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='icr.reglaicr'),
        ),
        migrations.DeleteModel(
            name='OperacionICR',
        ),
        migrations.DeleteModel(
            name='ResultadoICR',
        ),
        migrations.AddIndex(
            model_name='inscripcionicr',
            index=models.Index(fields=['estado'], name='icr_inscrip_estado_691b06_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcionicr',
            index=models.Index(fields=['tipo_productor'], name='icr_inscrip_tipo_pr_567e15_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcionicr',
            index=models.Index(fields=['bolsa', 'estado'], name='icr_inscrip_bolsa_i_84009f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='porcentajeicr',
            unique_together={('bolsa', 'tipo_productor')},
        ),
    ]
