# Generated by Django 6.0.3 on 2026-03-09 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoCamara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=255)),
                ('razon_social', models.CharField(blank=True, max_length=500)),
                ('nit', models.CharField(blank=True, max_length=50)),
                ('representante', models.CharField(blank=True, max_length=255)),
                ('tipo_doc', models.CharField(blank=True, max_length=20)),
                ('cedula', models.CharField(blank=True, max_length=50)),
                ('procesado_en', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='execution.execution')),
            ],
            options={
                'ordering': ['-procesado_en'],
            },
        ),
    ]
